export const data = [
    {
        "name": "Applied Geochemistry",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 1.03,
        "year": 2020,
        "category": "Geochemistry & Geophysics",
        "publisher": "Elsevier",
        "website": "https://www.journals.elsevier.com/applied-geochemistry",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 0
    },
    {
        "name": "Canadian Geotechnical Journal",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 1.09,
        "year": 2020,
        "category": "Geosciences, Multidisciplinary | Engineering, Geological",
        "publisher": "Canadian Science Publishing",
        "website": "https://cdnsciencepub.com/journal/cgj",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 1
    },
    {
        "name": "Chemical Engineering Journal",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 2.04,
        "year": 2020,
        "category": "Engineering, Chemical | Engineering, Environmental",
        "publisher": "Elsevier",
        "website": "https://www.journals.elsevier.com/chemical-engineering-journal",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 2
    },
    {
        "name": "Chemosphere",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 1.43,
        "year": 2020,
        "category": "Environmental Sciences",
        "publisher": "Elsevier",
        "website": "https://www.journals.elsevier.com/chemosphere",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 3
    },
    {
        "name": "Critical Reviews in Environmental Science and Technology",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 0.84,
        "year": 2020,
        "category": "Environmental Sciences",
        "publisher": "Taylor & Francis",
        "website": "https://www.tandfonline.com/journals/best20",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 4
    },
    {
        "name": "Environmental Science and Pollution Research",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 0.78,
        "year": 2020,
        "category": "Environmental Sciences",
        "publisher": "Springer",
        "website": "https://www.springer.com/journal/11356",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 5
    },
    {
        "name": "Environmental Earth Sciences",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 0.69,
        "year": 2020,
        "category": "Water Resources | Geosciences, Multidisciplinary | Environmental Sciences",
        "publisher": "Springer",
        "website": "https://www.springer.com/journal/12665",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 6
    },
    {
        "name": "Environmental Monitoring and Assessment",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 0.50,
        "year": 2020,
        "category": "Environmental Sciences",
        "publisher": "Springer",
        "website": "https://www.springer.com/journal/10661",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 7
    },
    {
        "name": "Environmental Science & Technology",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 1.45,
        "year": 2020,
        "category": "Environmental Sciences | Engineering, Environmental",
        "publisher": "ACS Publications",
        "website": "https://pubs.acs.org/loi/esthag",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 8
    },
    {
        "name": "Geochimica et Cosmochimica Acta",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 1.71,
        "year": 2020,
        "category": "Geochemistry & Geophysics",
        "publisher": "Elsevier",
        "website": "https://www.journals.elsevier.com/geochimica-et-cosmochimica-acta",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 9
    },
    {
        "name": "Hydrometallurgy",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 1.13,
        "year": 2020,
        "category": "Metallurgy & Metallurgical Engineering",
        "publisher": "Elsevier",
        "website": "https://www.journals.elsevier.com/hydrometallurgy",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 10
    },
    {
        "name": "International Journal of Mining, Reclamation and Environment",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 0.74,
        "year": 2020,
        "category": "Mining & Mineral Processing | Environmental Sciences",
        "publisher": "Taylor & Francis",
        "website": "https://www.tandfonline.com/journals/nsme20",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 11
    },
    {
        "name": "International Journal of Greenhouse Gas Control",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 0.64,
        "year": 2020,
        "category": "Engineering, Chemical | Energy & Fuels | Green & Sustainable Science & Technology | Engineering, Environmental",
        "publisher": "Elsevier",
        "website": "https://www.sciencedirect.com/journal/international-journal-of-greenhouse-gas-control",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 12
    },
    {
        "name": "Journal of Cleaner Production",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 1.51,
        "year": 2020,
        "category": "Green & Sustainable Science & Technology | Engineering, Environmental | Environmental Sciences",
        "publisher": "Elsevier",
        "website": "https://www.journals.elsevier.com/journal-of-cleaner-production",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 13
    },
    {
        "name": "Journal of Environmental Management",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 1.35,
        "year": 2020,
        "category": "Environmental Sciences",
        "publisher": "Elsevier",
        "website": "https://www.journals.elsevier.com/journal-of-environmental-management",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 14
    },
    {
        "name": "Journal of Environmental Quality",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 0.60,
        "year": 2020,
        "category": "Environmental Sciences",
        "publisher": "Wiley",
        "website": "https://acsess.onlinelibrary.wiley.com/journal/15372537",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 15
    },
    {
        "name": "Journal of Geochemical Exploration",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 1.27,
        "year": 2020,
        "category": "Geochemistry & Geophysics",
        "publisher": "Elsevier",
        "website": "https://www.journals.elsevier.com/journal-of-geochemical-exploration",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 16
    },
    {
        "name": "Journal of Quantitative Spectroscopy and Radiative Transfer",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 1.19,
        "year": 2020,
        "category": "Spectroscopy | Optics",
        "publisher": "Elsevier",
        "website": "https://www.journals.elsevier.com/journal-of-quantitative-spectroscopy-and-radiative-transfer",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 17
    },
    {
        "name": "Minerals",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 0.77,
        "year": 2020,
        "category": "Geochemistry & Geophysics | Mineralogy | Mining & Mineral Processing",
        "publisher": "MDPI",
        "website": "https://www.mdpi.com/journal/minerals",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 18
    },
    {
        "name": "Minerals Engineering",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 1.40,
        "year": 2020,
        "category": "Engineering, Chemical | Mining & Mineral Processing | Mineralogy",
        "publisher": "Elsevier",
        "website": "https://www.journals.elsevier.com/minerals-engineering",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 19
    },
    {
        "name": "Mine Water and The Environment",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 0.84,
        "year": 2020,
        "category": "Water Resources",
        "publisher": "Springer",
        "website": "https://www.springer.com/journal/10230",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 20
    },
    {
        "name": "Science of the Total Environment",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 1.66,
        "year": 2020,
        "category": "Environmental Sciences",
        "publisher": "Elsevier",
        "website": "https://www.journals.elsevier.com/science-of-the-total-environment",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 21
    },
    {
        "name": "Scientific Reports",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 0.80,
        "year": 2020,
        "category": "Multidisciplinary Sciences",
        "publisher": "Springer Nature",
        "website": "https://www.nature.com/srep/",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 22
    },
    {
        "name": "Vadose Zone Journal",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 0.82,
        "year": 2020,
        "category": "Water Resources | Soil Science | Environmental Sciences",
        "publisher": "Wiley",
        "website": "https://acsess.onlinelibrary.wiley.com/journal/15391663",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 23
    },
    {
        "name": "Water Air & Soil Pollution",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 0.55,
        "year": 2020,
        "category": "Meteorology & Atmospheric Sciences | Water Resources | Environmental Sciences",
        "publisher": "Springer",
        "website": "https://www.springer.com/journal/11270",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 24
    },
    {
        "name": "Chemical Geology",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 0.00,
        "year": 2020,
        "category": "",
        "publisher": "",
        "website": "",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 25
    },
    {
        "name": "ACS ES&T Water",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 0.00,
        "year": 2020,
        "category": "",
        "publisher": "",
        "website": "",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 26
    },
    {
        "name": "ACS Environmental Au",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 0.00,
        "year": 2020,
        "category": "",
        "publisher": "",
        "website": "",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 27
    },
    {
        "name": "Environmental Science: Processes & Impacts",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 0.00,
        "year": 2020,
        "category": "",
        "publisher": "",
        "website": "",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 28
    },
    {
        "name": "Environmental Earth Sciences",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 0.00,
        "year": 2020,
        "category": "",
        "publisher": "",
        "website": "",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 29
    },
    {
        "name": "Environmental Monitoring and Assessment",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 0.00,
        "year": 2020,
        "category": "",
        "publisher": "",
        "website": "",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 30
    },
    {
        "name": "International Journal of Environmental Science and Technology",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 0.00,
        "year": 2020,
        "category": "",
        "publisher": "",
        "website": "",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 31
    },
    {
        "name": "Frontiers in Earth Science",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 0.00,
        "year": 2020,
        "category": "",
        "publisher": "",
        "website": "",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 32
    },
    {
        "name": "JGR Biogeosciences",
        "IF5": "",
        "cHL": "",
        "SNIP": "",
        "JCI": 0.00,
        "year": 2020,
        "category": "",
        "publisher": "",
        "website": "",
        "articleType": "Research",
        "wordLimit": 0,
        "Sections": " | ",
        "id": 33
    }
];

